version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=onedrako_web_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user1234
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=user1234
    ports:
      - 5050:80